// <auto-generated />
using BuisnessLogic.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using System;

namespace CrfDesign.Server.WebAPI.Migrations
{
    [DbContext(typeof(CrfDesignContext))]
    partial class CrfDesignContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BuisnessLogic.CrfOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CrfPageComponentId")
                        .HasColumnType("int");

                    b.Property<int>("CrfQuestionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CrfPageComponentId");

                    b.ToTable("CrfOptions");
                });

            modelBuilder.Entity("BuisnessLogic.CrfOptionCategory", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<bool>("IsDeleted")
                    .HasColumnType("bit");

                b.Property<DateTime>("ModifiedDateTime")
                    .HasColumnType("datetime2");

                b.Property<string>("Name")
                    .HasColumnType("nvarchar(100)");

                b.HasKey("Id");

                b.ToTable("CrfOptionCategories");
            });

            modelBuilder.Entity("BuisnessLogic.CrfPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLockedForChanges")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CrfPages");
                });

            modelBuilder.Entity("BuisnessLogic.CrfPageComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CRFPageId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("CategoryId")
                         .HasColumnType("int");

                    b.Property<bool>("CategoryName")
                         .HasColumnType("nvarchar(100)");

                    b.Property<string>("QuestionText")
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("QuestionTypeId")
                        .HasColumnType("int");

                    b.Property<string>("RenderType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValidationPattern")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CRFPageId");

                    b.HasIndex("QuestionTypeId");

                    b.ToTable("CrfPageComponents");
                });

            modelBuilder.Entity("BuisnessLogic.QuestionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("QuestionTypes");
                });

            modelBuilder.Entity("BuisnessLogic.CrfOption", b =>
                {
                    b.HasOne("BuisnessLogic.CrfPageComponent", null)
                        .WithMany("Options")
                        .HasForeignKey("CrfPageComponentId");
                });

            modelBuilder.Entity("BuisnessLogic.CrfPageComponent", b =>
                {
                    b.HasOne("BuisnessLogic.CrfPage", "CrfPage")
                        .WithMany("Questions")
                        .HasForeignKey("CRFPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuisnessLogic.QuestionType", "QuestionType")
                        .WithMany()
                        .HasForeignKey("QuestionTypeId");

                    b.Navigation("CrfPage");

                    b.Navigation("QuestionType");
                });

            modelBuilder.Entity("BuisnessLogic.CrfPage", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("BuisnessLogic.CrfPageComponent", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
